# Generated by Django 4.1 on 2022-09-17 00:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyWatchList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched", models.BooleanField(default=False)),
                ("title", models.CharField(default="Judul", max_length=255)),
                (
                    "rating",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "release_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("review", models.TextField(default="Review")),
            ],
        ),
    ]
